# -------------------
# Jekyll Config
# --------------------
# Basic Jekyll configuration for site URLs and rendering
baseurl: ""                    # Subdirectory where site is hosted (empty if root)
url: "https://harian-elyoth.com" # Main domain URL
permalink: pretty             # URL structure for posts
markdown: kramdown           # Markdown processor
highlighter: rouge          # Syntax highlighter for code blocks

# Plugin Configuration
plugins:
  - jekyll-environment-variables  # Allows use of environment variables
  - jekyll-paginate              # Enables pagination for blog posts

# Pagination settings for blog posts
paginate: 6                  # Number of posts per page
paginate_path: "/blog/page/:num"  # URL structure for paginated pages

# Content Organization
collections_dir: collections # Root directory for all collections
collections:
  posts:                    # Blog posts collection
    output: true           # Generate individual post pages
    permalink: /blog/:path/ # URL structure for posts
  projects:
    output: true 
    permalink: /projects/:path/ # URL structure for projects

# Default Settings for Different Content Types
defaults:
  - scope:                  # Settings for blog posts
      path: ""
      type: posts
    values:
      layout: post
      weight: 999
  - scope:                  # Settings for projects
      path: ""
      type: projects
    values:
      layout: project
      weight: 999
  - scope:                  # Settings for images
      path: "images"
    values:
      image: true
  - scope:                  # Settings for category pages
      path: "categories"
    values:
      permalink: /category/:basename/
  - scope:                  # Settings for general pages
      path: "pages"
    values:
      permalink: /:basename/

# SCSS/CSS Configuration
sass:
  style: compact           # CSS output style (alternatives: nested, expanded, compressed)

# Files/Folders to Exclude from Build
exclude:                   # List of files not processed by Jekyll
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - netlify.toml

# -------------------
# Theme Config
# --------------------
# Basic Site Information
title: "Harian Elyoth"     # Site title
category_dir: 'category'   # Directory for category pages

# Color Scheme Configuration
colors:
  #light-mode colors      # Colors for light theme
  primary_bg: "#4392F1"   # Primary brand color
  primary_bg_2: "#eed2d9" # Secondary brand colors
  primary_bg_3: "#eed2d9"
  primary_text: "#f9fafb" # Text on primary backgrounds
  base_bg: "#ffffff"      # Main background colors
  base_bg_2: "#ebeef0"
  base_bg_3: "#d6dbe0"
  base_text: "#191a1a"    # Main text colors
  base_text_2: "#555555"
  logo_text: "#191a1a"    # Logo specific colors
  menu_text: "#191a1a"

  # dark-mode colors      # Colors for dark theme
  primary_bg_dark: "#4392F1"
  primary_bg_2_dark: "#eed2d9"
  primary_bg_3_dark: "#eed2d9"
  primary_text_dark: "#f9fafb"
  base_bg_dark: "#121418"
  base_bg_2_dark: "#1d2026"
  base_bg_3_dark: "#24272d"
  base_text_dark: "#F4F4F5"
  base_text_2_dark: "#D1D5DB"
  logo_text_dark: "#F4F4F5"
  menu_text_dark: "#F4F4F5"

# Typography Configuration
fonts:
  use_google_fonts: false  # Whether to load Google Fonts
  google_fonts_url: "https://fonts.googleapis.com/css2?&family=Schibsted+Grotesk:wght@400;500&family=Open+Sans:wght@300;400;500;600;700&family=Fira+Mono&display=swap"
  use_self_hosted_fonts: true # Whether to use locally hosted fonts
  heading: "Schibsted Grotesk" # Font families for different elements
  base: "Open Sans"
  monospace: "Fira Mono"
  logo: "Schibsted Grotesk"

# Logo Settings
logo:
  logo_text: "Harian Elyoth" # Text version of logo
  logo_image: assets/images/logo/logo.svg # Various logo image versions
  logo_image_mobile: assets/images/logo/logo-mobile.svg
  logo_image_invert: assets/images/logo/logo-invert.svg
  logo_image_invert_mobile: assets/images/logo/logo-invert-mobile.svg
  logo_image_desktop_height: "30px" # Logo dimensions
  logo_image_desktop_width: "30px"
  logo_image_mobile_height: "28px"
  logo_image_mobile_width: "28px"
  show_logo_image_on_mobile: true  # Logo visibility settings
  show_logo_image_on_desktop: true
  show_logo_text_on_mobile: false
  show_logo_text_on_desktop: true

# Header Configuration
header: 
  fixed: false           # Whether header stays fixed while scrolling

# Social Media/OpenGraph Settings
open_graph:
  meta_opengraph_type: "website" # OpenGraph metadata for social sharing
  meta_twitter_card: "summary"
  meta_twitter_site: "@zerostaticio"
  meta_twitter_creator: "@zerostaticio"

# Dark Mode Settings
darkmode:
  enable_dark_mode: true # Dark mode functionality
  show_dark_mode_toggle_in_header: false 
  show_dark_mode_toggle_in_bottom: true
  show_dark_mode_toggle_in_mobile_menu: false

# Cookie Consent Banner
cookie_banner:
  enabled: true         # Cookie consent functionality
  show_manage_cookies_at_bottom: true

# Analytics Integration
analytics:
  disable_analytics_on_localhost: false # Analytics configuration
  google_analytics_id: "" 
  gtm_id: "" 
  plausible_data_domain: "" 
  umami_data_website_id: "" 
  umami_src: "" 

# Comments System Configuration
comments:
  commento:
    enabled: false     # Commento comments system
  disqus:
    shortname: ""      # Disqus comments system

# Contact Form Settings
contact_form: 
  use_netlify_form: true    # Form handling configuration
  use_formspree_form: false
  formspree_endpoint: https://formspree.io/f/moqyklqv
  netlify_form_name: "contact"

# Menu Configuration
menu: 
  show_dropdown_items_in_mobile_menu: false # Mobile menu settings
  show_social_media_in_mobile_menu: true

# Footer Configuration
footer:
  enable_footer: false      # Footer visibility and content
  footer_title: "Harian Elyoth"
  footer_description: "Harian Elyoth is a blog about software engineering, project management, and life in South Korea."
  enable_social_media_icons: true
  enable_menu_footer_primary: true
  enable_menu_footer_secondary: false
  enable_menu_footer_tertiary: false
  footer_primary_menu_title: "Menu 1"
  footer_secondary_menu_title: "Menu 2"
  footer_tertiary_menu_title: "Menu 3"

# Bottom Bar Configuration
bottom:
  enable_bottom: true      # Bottom bar visibility and content
  enable_bottom_menu: true
  copyright_text: "© 2025 Elyoth Harian"
  show_rss_icon: true
